---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-tmprbac-rnemet-dev-v1-temprolebinding
  failurePolicy: Fail
  name: mtemprolebinding.kb.io
  rules:
  - apiGroups:
    - tmprbac.rnemet.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - temprolebindings
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tmprbac-rnemet-dev-v1-temprolebinding
  failurePolicy: Fail
  name: vtemprolebinding.kb.io
  rules:
  - apiGroups:
    - tmprbac.rnemet.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - temprolebindings
  sideEffects: None
