---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings/status
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings/status
  verbs:
  - get
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - tempclusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - tempclusterrolebindings/finalizers
  verbs:
  - update
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - tempclusterrolebindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - temprolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - temprolebindings/finalizers
  verbs:
  - update
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - temprolebindings/status
  verbs:
  - get
  - patch
  - update
