# permissions for end users to edit temprolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: temprolebinding-editor-role
rules:
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - temprolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - temprolebindings/status
  verbs:
  - get
