# permissions for end users to view temprolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: temprolebinding-viewer-role
rules:
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - temprolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - temprolebindings/status
  verbs:
  - get
