# permissions for end users to view tempclusterrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempclusterrolebinding-viewer-role
rules:
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - tempclusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tmprbac.rnemet.dev
  resources:
  - tempclusterrolebindings/status
  verbs:
  - get
