apiVersion: k3d.io/v1alpha3
kind: Simple
name: playground # name that you want to give to your cluster (will still be prefixed with `k3d-`)
servers: 1 # same as `--servers 1`
agents: 0 # same as `--agents 2`