apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: observer
rules:
- apiGroups: ["","apps"]
  resources: ["pods","deployments","secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: john
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ3ZUQ0NBYVVDQVFBd2VERUxNQWtHQTFVRUJoTUNVbE14RHpBTkJnTlZCQWdNQmxObGNtSnBZVEVSTUE4RwpBMVVFQnd3SVFtVnNaM0poWkdVeEVEQU9CZ05WQkFvTUIwUmxka04xWW1VeEVqQVFCZ05WQkFNTUNVcHZhRzRnClNtOW9iakVmTUIwR0NTcUdTSWIzRFFFSkFSWVFhbTlvYmtCa1pYWmpkV1JsTG1SbGRqQ0NBU0l3RFFZSktvWkkKaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFPdWlaZDVicVpGSlN6ZUl2NHZsK3JtSlRiNmU1OXV6V2VabQoybTVmcVRjR1B1N3JacVVIMWpCK1o4Wk94QUUrU0Y2ZWdoNnpUbWNPTDgwRUdtd1ltdXpnYkptR0RtTkc5U04rCk84Zi9oTisxOGh6SVlVOERyd1NwQ2p2Z1JFWThVNFNOSjRGV1E3aHZwNTVna3VPNUxFNVRrcUhiUWVlK1ArdlcKZFljRVI0ejRZOURCN0laeWlMYUdHSm5QajkyQ3REckFldUZablVrbzZkL0tXRk5YU2YxOGZzL1JaTG1kYWl3ZAoxY1N2ZjVlblI0TnpEeUEzU0lWMWcxZ285YVhINnkzcEVQK0xIQWpKUzRNZHNORCtYSmRTclM4Q3RjbVYvd3BuCjEzTHRRcWRJOGlYdWdHVXl0U3Q3SE1pYUFuQjY5emJjbDBISmxmQkU3dHMyZFJ1TkF6MENBd0VBQWFBQU1BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNickVvWlgvei8rNWhEVFQyY0hQdlUraW1kUXVLNzZEME9BKzdDMnlzOQpXZHNZb0txa0ZOdFYweFV6RDJmOWdBQnZiemN5WEtIS21yWUJqQ2R6QnQwU3RISmRXM1UxYm9WejhvMmlia093CnJhZVdMYnJtc0pUVndWN3JFN3ZRZDFvSDIxd09pZ0cxMzluS29ETFZISWxpdjFyaEw4ZDgxcTNzMVlFU091eXQKcXdma3lUR2gxRkR4bFhsbFd3QVB1UHBDdkY5UTBOWU5USEFKanFWUWlMcjdFMWV0WFV4aHA1VVpWNWtBamFjUAptOTRHUHNRSHZzbWNYTE1qWFJDZGtjMnFROGZWeHpZd1JxYVdkMDlhVUY4djhueEZEMjdzOTMxTGN3Z21qMWVBClpvMWhEQ2tqRmZ0V21NUjJhVnN3TWJlaW82amlOREF0S0ZPNi9IWHYyUnJiCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-kuttl